version: "3.8"

services:
  openbao1:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao1
    ports:
      - "8200:8200"
    volumes:
      - ./config/node1.hcl:/vault/config/config.hcl
      - ./data/node1:/vault/data
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    command: server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  openbao2:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao2
    ports:
      - "8202:8200"
    volumes:
      - ./config/node2.hcl:/vault/config/config.hcl
      - ./data/node2:/vault/data
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    command: server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

  openbao3:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao3
    ports:
      - "8204:8200"
    volumes:
      - ./config/node3.hcl:/vault/config/config.hcl
      - ./data/node3:/vault/data
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    command: server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  openbao_data: